name: example
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.2 <4.0.0"
  flutter: "3.10.2"

dependencies:
  flutter:
    sdk: flutter

  flutter_deriv_bloc_manager:
    git:
      url: git@github.com:regentmarkets/flutter-deriv-packages.git
      path: packages/deriv_bloc_manager
      ref: flutter-version-3

  flutter_bloc: ^8.1.3
  web_socket_channel: ^2.4.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
