name: dart_clean_architecture
description: A proposal for Flutter app architecture based on Clean architecture.

version: 1.0.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dev_dependencies:
  lints: ^1.0.0
  test: ^1.21.0
